# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      socket:
          # Define patterns to include dependencies in the group (based on
          # dependency name)
          patterns:
            - "socket.io" # A single dependency name
            - "@socket*"  # A wildcard string that matches multiple dependency names
          # Define patterns to exclude dependencies from the group (based on
          # dependency name)
          #exclude-patterns:
          #  - "gc_ruboconfig"
          #  - "gocardless-*
